### ISSUE TITLE
[DevTips] RIL on Android 12.1

### ISSUE THREAD

**Issue by sjllls** [linelessos/android_device_sony_tone-common#3]
@erikcas Sorry, I can't login telegram. So we can discuss here.
I found something useful on some msm8953 devices' commits. I think we need to switch to qcrild on Android 12.
https://github.com/meizucustoms/android_device_meizu_m1721/commit/95f8db5633bb2ccf587a4bc7b6285f0e8c226e14

https://github.com/meizucustoms/android_device_meizu_m1721/commits/lineage-19.1?after=403342a572cf23c13034620b7b6af0e0df717585+139&branch=lineage-19.1&qualified_name=refs%2Fheads%2Flineage-19.1

https://github.com/meizucustoms/android_device_meizu_m1721

It's amazing so many 3.10 kernel devices upgraded to 4.9.

**Comment by sjllls** [comment]
Now RIL runs. :)

**Comment by erikcas** [comment]
@sjllls cool!!
